language: csharp
solution: robotdotnet-wpilib.sln

os:
  - linux

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      libstdc++6-4.7-dbg

install:
  - nuget restore robotdotnet-wpilib.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=MonoDebug robotdotnet-wpilib.sln
