version: 2016.0.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: AppVeyor
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test_script:
- cmd: nunit-console.exe %APPVEYOR_BUILD_FOLDER%\WPILib.Tests\Output\WPILib.Tests.dll /framework:net-4.0