# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    versioningScheme: byBuildNumber
    arguments: '--configuration $(buildConfigurtion)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    publishTestResults: true
    versioningScheme: byBuildNumber
    arguments: '--configuration $(buildConfigurtion) --collect "Code coverage"'
  displayName: 'dotnet test $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    versioningScheme: byBuildNumber
    arguments: '--configuration $(buildConfigurtion)'
  displayName: 'dotnet pack $(buildConfiguration)'

- publish: $(System.DefaultWorkingDirectory)/nupkg
  artifact: Packages