name: dotnet package

on: [push]

jobs:
  build-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]
        target: [ 'win-x64', 'win-arm64' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build dotnet
        run: dotnet publish -r ${{ matrix.target }}
      - name: Run tests
        run: dotnet test

  build-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]
        target: [ 'linux-x64', 'linux-arm64' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build dotnet
        run: dotnet publish -r ${{ matrix.target }}
      - name: Run tests
        run: dotnet test
